### ISSUE TITLE
Windows test build broken since 938db3eb?

### ISSUE THREAD

**Issue by Sword-Smith** [TritonVM/triton-vm#244]
`cargo build` seems to work on Windows on current `master`, 63a5d1c110307dab73e28e5bb5a4187e2762b69f as of this issue. But ever since 938db3ebc3cc36da6ea7830036188ed61ba2d17f `cargo test` has not worked on Windows.

The problematic packages seem to be `rexpect` and `pty-process`, not sure how the latter one gets included though.

Should Windows builds and tests be added to CI?

**Comment by aszepieniec** [comment]
> Should Windows builds and tests be added to CI?

If possible, yes.

**Comment by jan-ferdinand** [comment]
Both of the mentioned dependencies are from Triton TUI and are used exclusively in integration tests.[^1] We can make compilation of the integration tests conditional on the target platform.

[^1]: Those tests are currently ignored because they do not play ball with `cargo tarpaulin`, the code coverage tool we use.
