### ISSUE TITLE
Prefix specifier to all environment variables

### ISSUE THREAD

**Issue by Sword-Smith** [TritonVM/triton-vm#267]
All environment variables used by `triton-vm` should have a prefix to avoid name collisions with other software. The prefix could for example be `TVM_`, `TRITONVM_`, or `TRITON_VM_`.

**Comment by jan-ferdinand** [comment]
I identify the following environment variables across our crates. Note that the scope of this issue is not the entire list, but only the first paragraph “Triton VM”.

### Triton VM

- `PROFILE_AS_YOU_GO`
- `TVM_CACHE_LDE_TRACE`[^1]

### twenty-first

- `MERKLE_TREE_PARALLELIZATION_CUTOFF`

### tasm-lib

- `TRITON_TUI`
- `DYING_TO_PROVE`

### tasm-lang

- `DYING_TO_PROVE`

### Neptune Core

- `DYING_TO_PROVE`

[^1]: soon
