### ISSUE TITLE
Add instruction `goto` and drop Jump Stack Table, instructions `call`, `return`, and `recurse`.

### ISSUE THREAD

**Issue by jan-ferdinand** [TritonVM/triton-vm#87]
The notion of “function” does not have to exist at the assembly level. Using only instruction `goto` + `d`, it is possible to achieve the same functionality. Compiling from a higher level language which does have functions is easy.

The correctness of a jump can be validated in the processor alone, by checking if the instruction pointer `ip` was modified correctly, *i.e.*, set to the argument `d` of `goto`. The Jump Stack Table is only needed to ensure that `return` and `recurse` modify the instruction pointer correctly.

My proposition is to
- delegate the notion of functions to the compiler,
- drop the Jump Stack Table, and
- replace all call-related instructions with `goto`.

The call graph is still static and can be checked before running the program. Most importantly, the design of Triton VM gets a lot simpler.

**Comment by aszepieniec** [comment]
I see two downsides with this approach.

**1. Branch to return.**

If the same function can be called from 20 different locations, the compiler must insert a sequence of 20 *else-if*s in that function's "return" section. This is needed so that control returns to the right caller.

**2. Stack hijacking.**

Which of the aforementioned branches to take must be determined by some value living on the stack. The programmer controls the stack, and so can trigger a "return" to the wrong location. If the program parses untrusted input, it is vulnerable to a [return-to-libc](https://en.wikipedia.org/wiki/Return-to-libc_attack) style attack.

I disagree with the proposition

> The call graph is still static [...]

The call graph is certainly constrained relative to an ISA with dynamic-destination gotos. The set of potential jump destinations is not arbitrary but fixed at compile time and hardcoded into the program. You can call this having a static call graph but I think that would be stretching the label to include notions it is meant to exclude.

There is always something dynamic about a concrete call graph, or at least whenever you run a meaningful computation. What makes the call graph static is that every possible concrete call graph fits into a tree structure that is known at compile time. This property is not satisfied if the programmer can control the location of return jumps.

**Comment by jan-ferdinand** [comment]
The obvious way to avoid this problem is code duplication. The resulting programs might become unwieldy, rendering the original proposition equally void.

**Comment by jan-ferdinand** [comment]
Given the above discussion, I'm not in favor of dropping the Jump Stack Table.
